name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  appVersion:
    runs-on: ubuntu-latest
    outputs:
      version_number: ${{ steps.vars.outputs.version_number }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      
    - name: set-output
      id: vars
      run: |
        version_number=$(sed -n 's/.*<h1>Wersja \([0-9.]*\)<\/h1>.*/\1/p' index.html)
        echo "version_number=${version_number}" >> "$GITHUB_OUTPUT"
      shell: bash

        
  dockerCI:
    needs: appVersion
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PAT }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: janfigurapollub/sem2-chmura-zad2:${{ needs.appVersion.outputs.version_number}}
       
  kubernetesCI:
    needs: [appVersion, dockerCI]
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          repository: janfig/sem2-chmura-config
          token: ${{ secrets.ACTIONS_TOKEN }}
      - run: |
          sed -i 's/janfigurapollub\/sem2-chmura-zad2:.*/janfigurapollub\/sem2-chmura-zad2:${{ needs.appVersion.outputs.version_number }}/g' webapp-dep.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -u
          git commit -m "version update ${{ needs.appVersion.outputs.version_number }}"
          git push
